name = "hono-crud-api"
main = "src/index.ts"
compatibility_date = "2024-12-24"

[[d1_databases]]
binding = "DB"
database_name = "todo-api-db"
database_id = "e6704fcb-0e3a-406b-bce8-60b6209588be"
migrations_dir = "./drizzle/migrations"
